//https://github.com/esterTion/yumesute_master_db_diff/blob/master/LoopMotionMaster.json
// Medium 2
// Small 1
export default [
    {
        Id: 101,
        TargetCharacterBaseId: "101",
        LoopSpeed: 1.06,
        Height: 158,
        Size: 2,
    },
    {
        Id: 102,
        TargetCharacterBaseId: "102",
        LoopSpeed: 0.89,
        Height: 158,
        Size: 2,
    },
    {
        Id: 103,
        TargetCharacterBaseId: "103",
        LoopSpeed: 0.88,
        Height: 154,
        Size: 2,
    },
    {
        Id: 104,
        TargetCharacterBaseId: "104",
        LoopSpeed: 0.95,
        Height: 146,
        Size: 1,
    },
    {
        Id: 105,
        TargetCharacterBaseId: "105",
        LoopSpeed: 0.77,
        Height: 157,
        Size: 2,
    },
    {
        Id: 106,
        TargetCharacterBaseId: "106",
        LoopSpeed: 1.21,
        Height: 165,
        Size: 2,
    },
    {
        Id: 107,
        TargetCharacterBaseId: "107",
        LoopSpeed: 0.8,
        Height: 164,
        Size: 2,
    },
    {
        Id: 110,
        TargetCharacterBaseId: "110",
        LoopSpeed: 0.85,
        Height: 162,
        Size: 2,
    },
    {
        Id: 111,
        TargetCharacterBaseId: "111",
        LoopSpeed: 0.75,
        Height: 156,
        Size: 2,
    },
    {
        Id: 201,
        TargetCharacterBaseId: "201",
        LoopSpeed: 0.94,
        Height: 165,
        Size: 2,
    },
    {
        Id: 202,
        TargetCharacterBaseId: "202",
        LoopSpeed: 1.15,
        Height: 154,
        Size: 2,
    },
    {
        Id: 203,
        TargetCharacterBaseId: "203",
        LoopSpeed: 1.07,
        Height: 162,
        Size: 2,
    },
    {
        Id: 204,
        TargetCharacterBaseId: "204",
        LoopSpeed: 1.13,
        Height: 158,
        Size: 2,
    },
    {
        Id: 205,
        TargetCharacterBaseId: "205",
        LoopSpeed: 1.03,
        Height: 147,
        Size: 1,
    },
    {
        Id: 206,
        TargetCharacterBaseId: "206",
        LoopSpeed: 0.78,
        Height: 156,
        Size: 2,
    },
    {
        Id: 301,
        TargetCharacterBaseId: "301",
        LoopSpeed: 1,
        Height: 159,
        Size: 2,
    },
    {
        Id: 302,
        TargetCharacterBaseId: "302",
        LoopSpeed: 1.18,
        Height: 163,
        Size: 2,
    },
    {
        Id: 303,
        TargetCharacterBaseId: "303",
        LoopSpeed: 0.84,
        Height: 151,
        Size: 1,
    },
    {
        Id: 304,
        TargetCharacterBaseId: "304",
        LoopSpeed: 1.05,
        Height: 168,
        Size: 2,
    },
    {
        Id: 305,
        TargetCharacterBaseId: "305",
        LoopSpeed: 0.83,
        Height: 155,
        Size: 2,
    },
    {
        Id: 306,
        TargetCharacterBaseId: "306",
        LoopSpeed: 1.1,
        Height: 155,
        Size: 2,
    },
    {
        Id: 401,
        TargetCharacterBaseId: "401",
        LoopSpeed: 1.19,
        Height: 158,
        Size: 2,
    },
    {
        Id: 402,
        TargetCharacterBaseId: "402",
        LoopSpeed: 1.16,
        Height: 156,
        Size: 2,
    },
    {
        Id: 403,
        TargetCharacterBaseId: "403",
        LoopSpeed: 0.99,
        Height: 163,
        Size: 2,
    },
    {
        Id: 404,
        TargetCharacterBaseId: "404",
        LoopSpeed: 1.1,
        Height: 160,
        Size: 2,
    },
    {
        Id: 405,
        TargetCharacterBaseId: "405",
        LoopSpeed: 0.76,
        Height: 151,
        Size: 1,
    },
    {
        Id: 406,
        TargetCharacterBaseId: "406",
        LoopSpeed: 0.97,
        Height: 164,
        Size: 2,
    },
    {
        Id: 407,
        TargetCharacterBaseId: "407",
        LoopSpeed: 0.86,
        Height: 159,
        Size: 2,
    },
    {
        Id: 408,
        TargetCharacterBaseId: "408",
        LoopSpeed: 1.19,
        Height: 150,
        Size: 2,
    },
    {
        Id: 409,
        TargetCharacterBaseId: "409",
        LoopSpeed: 1.25,
        Height: 150,
        Size: 2,
    },
    {
        Id: 501,
        TargetCharacterBaseId: "501",
        LoopSpeed: 0.93,
        Height: 166,
        Size: 2,
    },
    {
        Id: 502,
        TargetCharacterBaseId: "502",
        LoopSpeed: 1.17,
        Height: 146,
        Size: 1,
    },
    {
        Id: 503,
        TargetCharacterBaseId: "503",
        LoopSpeed: 1.07,
        Height: 160,
        Size: 2,
    },
    {
        Id: 504,
        TargetCharacterBaseId: "504",
        LoopSpeed: 0.91,
        Height: 162,
        Size: 2,
    },
    {
        Id: 505,
        TargetCharacterBaseId: "505",
        LoopSpeed: 0.96,
        Height: 156,
        Size: 2,
    },
    {
        Id: 506,
        TargetCharacterBaseId: "506",
        LoopSpeed: 1.04,
        Height: 146,
        Size: 1,
    },
    {
        Id: 507,
        TargetCharacterBaseId: "507",
        LoopSpeed: 1.15,
        Height: 146,
        Size: 1,
    },
    {
        Id: 508,
        TargetCharacterBaseId: "508",
        LoopSpeed: 1.2,
        Height: 150,
        Size: 1,
    },
    {
        Id: 509,
        TargetCharacterBaseId: "509",
        LoopSpeed: 1.07,
        Height: 165,
        Size: 2,
    },
    {
        Id: 511,
        TargetCharacterBaseId: "511",
        LoopSpeed: 1.16,
        Height: 154,
        Size: 1,
    },
    {
        Id: 513,
        TargetCharacterBaseId: "513",
        LoopSpeed: 1.07,
        Height: 165,
        Size: 2,
    },
    {
        Id: 514,
        TargetCharacterBaseId: "514",
        LoopSpeed: 1.07,
        Height: 147,
        Size: 2,
    },
    {
        Id: 515,
        TargetCharacterBaseId: "515",
        LoopSpeed: 0.89,
        Height: 145,
        Size: 2,
    },
    {
        Id: 516,
        TargetCharacterBaseId: "516",
        LoopSpeed: 1,
        Height: 165,
        Size: 2,
    },
    {
        Id: 517,
        TargetCharacterBaseId: "517",
        LoopSpeed: 0.95,
        Height: 164,
        Size: 2,
    },
    {
        Id: 518,
        TargetCharacterBaseId: "518",
        LoopSpeed: 1.08,
        Height: 170,
        Size: 2,
    },
    {
        Id: 519,
        TargetCharacterBaseId: "519",
        LoopSpeed: 0.89,
        Height: 164,
        Size: 2,
    },
    {
        Id: 520,
        TargetCharacterBaseId: "520",
        LoopSpeed: 1.25,
        Height: 152,
        Size: 1,
    },
    {
        Id: 521,
        TargetCharacterBaseId: "521",
        LoopSpeed: 1.1,
        Height: 146,
        Size: 1,
    },
    {
        Id: 522,
        TargetCharacterBaseId: "522",
        LoopSpeed: 1,
        Height: 164,
        Size: 2,
    },
    {
        Id: 901,
        TargetCharacterBaseId: "901",
        LoopSpeed: 1.08,
        Height: 157,
        Size: 2,
    },
    {
        Id: 902,
        TargetCharacterBaseId: "902",
        LoopSpeed: 1,
        Height: 160,
        Size: 2,
    },
    {
        Id: 904,
        TargetCharacterBaseId: "904",
        LoopSpeed: 0.95,
        Height: 162,
        Size: 2,
    },
    {
        Id: 906,
        TargetCharacterBaseId: "906",
        LoopSpeed: 1.1,
        Height: 156,
        Size: 2,
    },
    {
        Id: 909,
        TargetCharacterBaseId: "909",
        LoopSpeed: 1.25,
        Height: 154,
        Size: 2,
    },
];
